main = ".worker-next/index.mjs"
name = "actions"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
routes = [{ pattern = "civicdashboard.ca", custom_domain = true }]

[observability.logs]
enabled = true
